import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialSchema1784225014049 implements MigrationInterface {
    name = 'InitialSchema1784225014049'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TYPE "public"."PushToken_device_type_enum" AS ENUM('IOS', 'ANDROID')`);
        await queryRunner.query(`CREATE TABLE "PushToken" ("created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP DEFAULT now(), "deleted_at" TIMESTAMP, "token_id" SERIAL NOT NULL, "fcm_token" character varying(255) NOT NULL, "device_type" "public"."PushToken_device_type_enum" NOT NULL, "user_id" integer, CONSTRAINT "PK_fe43547c08a59044881729356ac" PRIMARY KEY ("token_id")); COMMENT ON COLUMN "PushToken"."created_at" IS '생성시간'; COMMENT ON COLUMN "PushToken"."updated_at" IS '수정시간'; COMMENT ON COLUMN "PushToken"."deleted_at" IS 'softDelete 삭제시간'; COMMENT ON COLUMN "PushToken"."fcm_token" IS 'FCM 디바이스 토큰'; COMMENT ON COLUMN "PushToken"."device_type" IS '디바이스 종류'`);
        await queryRunner.query(`CREATE TABLE "Reminder" ("created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP DEFAULT now(), "reminder_id" SERIAL NOT NULL, "days" jsonb DEFAULT '["MON","TUE","WED","THU","FRI","SAT","SUN"]', "time" TIME DEFAULT '18:00:00', "alarm_id" integer, CONSTRAINT "REL_75126e2ee6a6abfdc38a5526d6" UNIQUE ("alarm_id"), CONSTRAINT "PK_3ff4b8c2acc9597172137767f7c" PRIMARY KEY ("reminder_id")); COMMENT ON COLUMN "Reminder"."created_at" IS '생성시간'; COMMENT ON COLUMN "Reminder"."updated_at" IS '수정시간'; COMMENT ON COLUMN "Reminder"."days" IS '알람 요일'; COMMENT ON COLUMN "Reminder"."time" IS '알람 시간'`);
        await queryRunner.query(`CREATE TABLE "UserAlarm" ("created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP DEFAULT now(), "alarm_id" SERIAL NOT NULL, "is_push" boolean NOT NULL DEFAULT false, "is_diary" boolean NOT NULL DEFAULT false, "is_diary_reply" boolean NOT NULL DEFAULT false, "user_id" integer, CONSTRAINT "REL_dc7e881262c51d946a729ba2dc" UNIQUE ("user_id"), CONSTRAINT "PK_71063b3c1bdbeede92b4e9630af" PRIMARY KEY ("alarm_id")); COMMENT ON COLUMN "UserAlarm"."created_at" IS '생성시간'; COMMENT ON COLUMN "UserAlarm"."updated_at" IS '수정시간'; COMMENT ON COLUMN "UserAlarm"."is_push" IS 'PUSH 알람 여부'; COMMENT ON COLUMN "UserAlarm"."is_diary" IS '일기 작성 알람 여부'; COMMENT ON COLUMN "UserAlarm"."is_diary_reply" IS '일기 답장 알람 여부'`);
        await queryRunner.query(`CREATE TABLE "User" ("user_id" SERIAL NOT NULL, "name" character varying(30) NOT NULL, "email" character varying(255), "profile_image_url" character varying(255), "password" character varying(255), "provider_id" character varying(200), "is_ai_summary" boolean NOT NULL DEFAULT false, "credentials_changed_at" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "UQ_4a257d2c9837248d70640b3e36e" UNIQUE ("email"), CONSTRAINT "UQ_6102ee0e389120de301b332c15b" UNIQUE ("provider_id"), CONSTRAINT "PK_af4be3eb77a4bdbafac6f808ff3" PRIMARY KEY ("user_id")); COMMENT ON COLUMN "User"."name" IS '사용자 이름'; COMMENT ON COLUMN "User"."email" IS '이메일'; COMMENT ON COLUMN "User"."profile_image_url" IS '프로필 이미지'; COMMENT ON COLUMN "User"."password" IS '비밀번호'; COMMENT ON COLUMN "User"."provider_id" IS '소셜 로그인 식별자 아이디'; COMMENT ON COLUMN "User"."is_ai_summary" IS 'AI 일기 요약 여부'; COMMENT ON COLUMN "User"."credentials_changed_at" IS '인증 정보 변경일'; COMMENT ON COLUMN "User"."created_at" IS '생성일'; COMMENT ON COLUMN "User"."updated_at" IS '수정일'; COMMENT ON COLUMN "User"."deleted_at" IS '삭제일'`);
        await queryRunner.query(`CREATE TYPE "public"."agreement_type_enum" AS ENUM('TERMS_OF_SERVICE', 'PRIVACY_POLICY', 'MARKETING')`);
        await queryRunner.query(`CREATE TABLE "user_agreements" ("user_agreement_id" SERIAL NOT NULL, "agreement_type" "public"."agreement_type_enum" NOT NULL, "agreement_version" character varying(20) NOT NULL, "is_agreed" boolean NOT NULL, "agreed_at" TIMESTAMP, "revoked_at" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP DEFAULT now(), "user_id" integer NOT NULL, CONSTRAINT "PK_985fa5707488626694f25666989" PRIMARY KEY ("user_agreement_id")); COMMENT ON COLUMN "user_agreements"."agreement_type" IS '약관 종류'; COMMENT ON COLUMN "user_agreements"."agreement_version" IS '약관 버전'; COMMENT ON COLUMN "user_agreements"."is_agreed" IS '동의 여부'; COMMENT ON COLUMN "user_agreements"."agreed_at" IS '동의일'; COMMENT ON COLUMN "user_agreements"."revoked_at" IS '철회일'; COMMENT ON COLUMN "user_agreements"."created_at" IS '생성일'; COMMENT ON COLUMN "user_agreements"."updated_at" IS '수정일'`);
        await queryRunner.query(`CREATE TYPE "public"."RefreshToken_device_type_enum" AS ENUM('IOS', 'ANDROID')`);
        await queryRunner.query(`CREATE TABLE "RefreshToken" ("refresh_token_id" SERIAL NOT NULL, "token_hash" character varying(255) NOT NULL, "device_id" character varying(255), "device_type" "public"."RefreshToken_device_type_enum", "expires_at" TIMESTAMP NOT NULL, "revoked_at" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP DEFAULT now(), "user_id" integer NOT NULL, CONSTRAINT "PK_71837542575fdae0fb708bfd458" PRIMARY KEY ("refresh_token_id")); COMMENT ON COLUMN "RefreshToken"."token_hash" IS '리프레시 토큰 해시값'; COMMENT ON COLUMN "RefreshToken"."device_id" IS '디바이스 식별자'; COMMENT ON COLUMN "RefreshToken"."device_type" IS '디바이스 종류'; COMMENT ON COLUMN "RefreshToken"."expires_at" IS '만료일'; COMMENT ON COLUMN "RefreshToken"."revoked_at" IS '폐기일'; COMMENT ON COLUMN "RefreshToken"."created_at" IS '생성일'; COMMENT ON COLUMN "RefreshToken"."updated_at" IS '수정일'`);
        await queryRunner.query(`CREATE TYPE "public"."schedule_repeat_group_repeat_type_enum" AS ENUM('NONE', 'MULTIPLE', 'PERIOD', 'WEEKLY')`);
        await queryRunner.query(`CREATE TABLE "ScheduleRepeatGroup" ("group_id" SERIAL NOT NULL, "user_id" integer NOT NULL, "repeat_type" "public"."schedule_repeat_group_repeat_type_enum" NOT NULL, "repeat_start_date" date, "repeat_end_date" date, "repeat_days" character varying(50), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP DEFAULT now(), CONSTRAINT "PK_13d5e257d6a23c8925ff4ce87ea" PRIMARY KEY ("group_id"))`);
        await queryRunner.query(`CREATE TABLE "schedule" ("schedule_id" SERIAL NOT NULL, "user_id" integer NOT NULL, "category_id" integer NOT NULL, "group_id" integer, "title" character varying(50) NOT NULL, "content" text, "date" date NOT NULL, "is_completed" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP DEFAULT now(), CONSTRAINT "PK_e2f8b8dde7d240896cd58c669a2" PRIMARY KEY ("schedule_id"))`);
        await queryRunner.query(`CREATE TYPE "public"."diary_type_enum" AS ENUM('QUESTION', 'FREE')`);
        await queryRunner.query(`CREATE TABLE "diary" ("created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP DEFAULT now(), "deleted_at" TIMESTAMP, "diary_id" SERIAL NOT NULL, "user_id" integer NOT NULL, "diary_type" "public"."diary_type_enum" NOT NULL, "diary_title" character varying(50) NOT NULL, "content" text NOT NULL, "ai_summary" text, CONSTRAINT "PK_3f76d00b404ad8c4bd80e12da8e" PRIMARY KEY ("diary_id")); COMMENT ON COLUMN "diary"."created_at" IS '생성시간'; COMMENT ON COLUMN "diary"."updated_at" IS '수정시간'; COMMENT ON COLUMN "diary"."deleted_at" IS 'softDelete 삭제시간'; COMMENT ON COLUMN "diary"."user_id" IS '사용자 아이디'; COMMENT ON COLUMN "diary"."diary_type" IS '일기 유형'; COMMENT ON COLUMN "diary"."diary_title" IS '일기 제목'; COMMENT ON COLUMN "diary"."content" IS '일기 내용'; COMMENT ON COLUMN "diary"."ai_summary" IS 'AI 일기 요약'`);
        await queryRunner.query(`CREATE TABLE "diary_image" ("created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP DEFAULT now(), "deleted_at" TIMESTAMP, "diary_image_id" SERIAL NOT NULL, "diary_id" integer NOT NULL, "image_url" character varying(200) NOT NULL, CONSTRAINT "PK_64bbbdcdfb976e5aad8fbe2d870" PRIMARY KEY ("diary_image_id")); COMMENT ON COLUMN "diary_image"."created_at" IS '생성시간'; COMMENT ON COLUMN "diary_image"."updated_at" IS '수정시간'; COMMENT ON COLUMN "diary_image"."deleted_at" IS 'softDelete 삭제시간'; COMMENT ON COLUMN "diary_image"."diary_id" IS '일기 아이디'; COMMENT ON COLUMN "diary_image"."image_url" IS '이미지 주소(S3 URL)'`);
        await queryRunner.query(`CREATE TYPE "public"."category_color_enum" AS ENUM('BLUE', 'BROWN', 'GREEN', 'PURPLE', 'PINK')`);
        await queryRunner.query(`CREATE TABLE "Category" ("category_id" SERIAL NOT NULL, "category_name" character varying(30) NOT NULL, "category_color" "public"."category_color_enum" NOT NULL, "user_id" integer NOT NULL, "category_order" integer NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "PK_0132db99add61303c1f236142bd" PRIMARY KEY ("category_id")); COMMENT ON COLUMN "Category"."category_name" IS '카테고리명'; COMMENT ON COLUMN "Category"."category_color" IS '카테고리 색'; COMMENT ON COLUMN "Category"."user_id" IS '사용자 아이디'; COMMENT ON COLUMN "Category"."category_order" IS '카테고리 순서'; COMMENT ON COLUMN "Category"."created_at" IS '생성일'; COMMENT ON COLUMN "Category"."updated_at" IS '수정일'; COMMENT ON COLUMN "Category"."deleted_at" IS '삭제일'`);
        await queryRunner.query(`CREATE TYPE "public"."email_verification_purpose_enum" AS ENUM('SIGNUP', 'PASSWORD_RESET')`);
        await queryRunner.query(`CREATE TABLE "EmailVerification" ("email_verification_id" SERIAL NOT NULL, "email" character varying(255) NOT NULL, "purpose" "public"."email_verification_purpose_enum" NOT NULL, "code_hash" character varying(64) NOT NULL, "code_expires_at" TIMESTAMP NOT NULL, "failed_attempts" integer NOT NULL DEFAULT '0', "sent_at" TIMESTAMP NOT NULL, "verified_at" TIMESTAMP, "verification_token_hash" character varying(64), "verification_token_expires_at" TIMESTAMP, "consumed_at" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_EMAIL_VERIFICATION_EMAIL_PURPOSE" UNIQUE ("email", "purpose"), CONSTRAINT "PK_bdcd00d34cc65856f8b9baa8912" PRIMARY KEY ("email_verification_id"))`);
        await queryRunner.query(`CREATE TABLE "Question" ("question_id" SERIAL NOT NULL, "content" text NOT NULL, "target_date" date NOT NULL, CONSTRAINT "UQ_a078f411f3198ebd9f7c69f6dc1" UNIQUE ("target_date"), CONSTRAINT "PK_39378c404a11a94850d7c6ee0de" PRIMARY KEY ("question_id")); COMMENT ON COLUMN "Question"."question_id" IS '질문ID'; COMMENT ON COLUMN "Question"."content" IS '질문내용'; COMMENT ON COLUMN "Question"."target_date" IS '질문 날짜'`);
        await queryRunner.query(`CREATE TABLE "DiaryQuestion" ("diary_question_id" SERIAL NOT NULL, "is_written" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "question_id" integer NOT NULL, "diary_id" integer, CONSTRAINT "REL_af4bd8f20531902a8b52b84aac" UNIQUE ("diary_id"), CONSTRAINT "PK_aa19a1067dc1e4bd241bfb89453" PRIMARY KEY ("diary_question_id")); COMMENT ON COLUMN "DiaryQuestion"."diary_question_id" IS '일기-질문 아이디'; COMMENT ON COLUMN "DiaryQuestion"."created_at" IS '생성일자'; COMMENT ON COLUMN "DiaryQuestion"."question_id" IS '질문ID'`);
        await queryRunner.query(`CREATE TABLE "Answer" ("answer_id" SERIAL NOT NULL, "answer" text NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "diary_id" integer NOT NULL, CONSTRAINT "REL_856c60f9641d3932a537ebd2c2" UNIQUE ("diary_id"), CONSTRAINT "PK_cfb4d2205f97c90dea87488bc54" PRIMARY KEY ("answer_id")); COMMENT ON COLUMN "Answer"."created_at" IS '생성일'`);
        await queryRunner.query(`ALTER TABLE "PushToken" ADD CONSTRAINT "FK_57109ff77e595b05c4025194360" FOREIGN KEY ("user_id") REFERENCES "User"("user_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Reminder" ADD CONSTRAINT "FK_75126e2ee6a6abfdc38a5526d62" FOREIGN KEY ("alarm_id") REFERENCES "UserAlarm"("alarm_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "UserAlarm" ADD CONSTRAINT "FK_dc7e881262c51d946a729ba2dc0" FOREIGN KEY ("user_id") REFERENCES "User"("user_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_agreements" ADD CONSTRAINT "FK_94748d77c6aecf02feb4b751ba4" FOREIGN KEY ("user_id") REFERENCES "User"("user_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "RefreshToken" ADD CONSTRAINT "FK_52a7dbaebd1bec036be1d145755" FOREIGN KEY ("user_id") REFERENCES "User"("user_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "schedule" ADD CONSTRAINT "FK_b9579e4a3a46e2afdae0b757048" FOREIGN KEY ("group_id") REFERENCES "ScheduleRepeatGroup"("group_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "DiaryQuestion" ADD CONSTRAINT "FK_77aac56c229b6ef3631138a05c0" FOREIGN KEY ("question_id") REFERENCES "Question"("question_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "DiaryQuestion" ADD CONSTRAINT "FK_af4bd8f20531902a8b52b84aac3" FOREIGN KEY ("diary_id") REFERENCES "diary"("diary_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Answer" ADD CONSTRAINT "FK_856c60f9641d3932a537ebd2c2c" FOREIGN KEY ("diary_id") REFERENCES "diary"("diary_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "Answer" DROP CONSTRAINT "FK_856c60f9641d3932a537ebd2c2c"`);
        await queryRunner.query(`ALTER TABLE "DiaryQuestion" DROP CONSTRAINT "FK_af4bd8f20531902a8b52b84aac3"`);
        await queryRunner.query(`ALTER TABLE "DiaryQuestion" DROP CONSTRAINT "FK_77aac56c229b6ef3631138a05c0"`);
        await queryRunner.query(`ALTER TABLE "schedule" DROP CONSTRAINT "FK_b9579e4a3a46e2afdae0b757048"`);
        await queryRunner.query(`ALTER TABLE "RefreshToken" DROP CONSTRAINT "FK_52a7dbaebd1bec036be1d145755"`);
        await queryRunner.query(`ALTER TABLE "user_agreements" DROP CONSTRAINT "FK_94748d77c6aecf02feb4b751ba4"`);
        await queryRunner.query(`ALTER TABLE "UserAlarm" DROP CONSTRAINT "FK_dc7e881262c51d946a729ba2dc0"`);
        await queryRunner.query(`ALTER TABLE "Reminder" DROP CONSTRAINT "FK_75126e2ee6a6abfdc38a5526d62"`);
        await queryRunner.query(`ALTER TABLE "PushToken" DROP CONSTRAINT "FK_57109ff77e595b05c4025194360"`);
        await queryRunner.query(`DROP TABLE "Answer"`);
        await queryRunner.query(`DROP TABLE "DiaryQuestion"`);
        await queryRunner.query(`DROP TABLE "Question"`);
        await queryRunner.query(`DROP TABLE "EmailVerification"`);
        await queryRunner.query(`DROP TYPE "public"."email_verification_purpose_enum"`);
        await queryRunner.query(`DROP TABLE "Category"`);
        await queryRunner.query(`DROP TYPE "public"."category_color_enum"`);
        await queryRunner.query(`DROP TABLE "diary_image"`);
        await queryRunner.query(`DROP TABLE "diary"`);
        await queryRunner.query(`DROP TYPE "public"."diary_type_enum"`);
        await queryRunner.query(`DROP TABLE "schedule"`);
        await queryRunner.query(`DROP TABLE "ScheduleRepeatGroup"`);
        await queryRunner.query(`DROP TYPE "public"."schedule_repeat_group_repeat_type_enum"`);
        await queryRunner.query(`DROP TABLE "RefreshToken"`);
        await queryRunner.query(`DROP TYPE "public"."RefreshToken_device_type_enum"`);
        await queryRunner.query(`DROP TABLE "user_agreements"`);
        await queryRunner.query(`DROP TYPE "public"."agreement_type_enum"`);
        await queryRunner.query(`DROP TABLE "User"`);
        await queryRunner.query(`DROP TABLE "UserAlarm"`);
        await queryRunner.query(`DROP TABLE "Reminder"`);
        await queryRunner.query(`DROP TABLE "PushToken"`);
        await queryRunner.query(`DROP TYPE "public"."PushToken_device_type_enum"`);
    }

}
